name: beadneko
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  dio: ^5.9.0
  flutter_smart_dialog: ^4.9.8+9
  cached_network_image: ^3.4.1
  flutter_ytnavigator: ^0.0.7
  flutter_ytlog: ^0.0.4
  flutter_spinkit: ^5.2.2
  google_fonts: ^6.1.0
  
  # Image handling
  image_picker: ^1.2.1
  image: ^4.7.1
  image_gallery_saver_plus: ^4.0.1
  
  # Storage
  path_provider: ^2.1.5
  
  package_info_plus: ^9.0.0
  
  # Utils
  permission_handler: ^12.0.1
  share_plus: ^12.0.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  test: ^1.26.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
